os: [linux, osx] # ostrost/ostent flagged multi-os
language: c # Go runtime is managed with gvm
sudo: false
env:
  global:
    - DPL_DIR=~/deploy # ~/deploy is outside the clone dir
    - GO_VERSION: 1.7
install:
  - source ./tools/sh/env.sh install_1
  - source ./tools/sh/env.sh install_2 $TRAVIS_REPO_SLUG
  - source ./tools/sh/env.sh install_3
  - source ./tools/sh/env.sh Gmake init
script:
  - source ./tools/sh/env.sh Gmake --always-make test all
before_deploy:
  - source ./tools/sh/env.sh before_deploy_1
  - source ./tools/sh/env.sh before_deploy_2
  - source ./tools/sh/env.sh before_deploy_3
  - source ./tools/sh/env.sh before_deploy_4
  - set +e # off fatal errors for travis-dpl
after_deploy:
  - set -e # back to fatal errors
  - source ./tools/sh/env.sh cleanup_deploy
deploy:
  file_glob: true
  file: $HOME/deploy/*
  on: {tags: true}
  provider: releases
  prerelease: true
  api_key:
    secure: >
      EFMPpR2rZkCdlfWuz7bE4ji3/0OL+fgIq+lXJ5SWDUG7aYWVqlLpR1hYXb0yqy8YA2Rg3xvAfPY/sFZvCyUMv0Wx1ZhiVzNvAUduzYFqovvHoYS4nuv0bXWis4YBnx7zJ7uikl5aGAOB8g0L+ofsUAswlDU5M9g9stDG4upWSgw=
